"""Initial migration

Revision ID: 2ebff5ed40e0
Revises: 
Create Date: 2026-01-31 09:37:27.918428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebff5ed40e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour_segment', sa.String(length=20), nullable=False),
    sa.Column('bill_count', sa.Integer(), nullable=True),
    sa.Column('is_peak_hour', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary_multiplier', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('system_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('STAFF', 'MANAGER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('employment_type', sa.Enum('PART_TIME', 'FULL_TIME', name='employmenttype'), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=False),
    sa.Column('salary_percentage', sa.Float(), nullable=True),
    sa.Column('meal_support_eligible', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='shifttype'), nullable=False),
    sa.Column('scheduled_start', sa.Time(), nullable=False),
    sa.Column('scheduled_end', sa.Time(), nullable=False),
    sa.Column('actual_checkin', sa.Time(), nullable=True),
    sa.Column('actual_checkout', sa.Time(), nullable=True),
    sa.Column('late_minutes', sa.Integer(), nullable=True),
    sa.Column('early_departure_minutes', sa.Integer(), nullable=True),
    sa.Column('total_work_hours', sa.Float(), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('is_early_bird', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_work_hours', sa.Float(), nullable=True),
    sa.Column('total_shifts', sa.Integer(), nullable=True),
    sa.Column('late_count', sa.Integer(), nullable=True),
    sa.Column('total_penalty', sa.Float(), nullable=True),
    sa.Column('total_reward', sa.Float(), nullable=True),
    sa.Column('meal_support_amount', sa.Float(), nullable=True),
    sa.Column('advance_payment', sa.Float(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'PAID', name='payrollstatus'), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'year', name='unique_user_month_year')
    )
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=True),
    sa.Column('type', sa.Enum('PUNCTUAL', 'SALES', 'REVIEW', 'GAME', 'TEST', name='rewardtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('LATE', 'BROKEN_ITEM', 'HYGIENE', 'OTHER', name='violationtype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('penalty_amount', sa.Float(), nullable=True),
    sa.Column('late_count_in_month', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('week_end_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'LOCKED', name='schedulestatus'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='shifttype'), nullable=False),
    sa.Column('shift_start_time', sa.Time(), nullable=False),
    sa.Column('shift_end_time', sa.Time(), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_and_condition', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['work_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_shifts')
    op.drop_table('work_schedules')
    op.drop_table('violations')
    op.drop_table('rewards')
    op.drop_table('payroll')
    op.drop_table('notifications')
    op.drop_table('attendance_records')
    op.drop_table('users')
    op.drop_table('system_config')
    op.drop_table('holidays')
    op.drop_table('customer_traffic')
    # ### end Alembic commands ###
